language: emacs-lisp
before_install:
  - curl -fsSkL https://gist.github.com/rejeep/7736123/raw | sh
  - export PATH="/home/travis/.cask/bin:$PATH"
  - export PATH="/home/travis/.evm/bin:$PATH"
  - evm install $EVM_EMACS --use
  - cask
env:
  global:
    - CURL=curl -fsSkL --retry 9 --retry-delay 9
  matrix:
    - EVM_EMACS=emacs-23.4-bin
    - EVM_EMACS=emacs-24.1-bin
    - EVM_EMACS=emacs-24.2-bin
    - EVM_EMACS=emacs-24.3-bin
install:
  - if ! test $EVM_EMACS = emacs-24.3-bin; then
      $CURL https://raw.github.com/emacsmirror/cl-lib/master/cl-lib.el -o cl-lib.el;
    fi
script:
  - emacs --version
  - make test
